# Generated by Django 5.1.2 on 2024-12-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available.\n\n'),
        ),
    ]
