# Generated by Django 5.1.2 on 2024-12-12 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_booksource_booksourcereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booksource',
            unique_together={('user', 'book')},
        ),
        migrations.AddField(
            model_name='booksource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='books.book'),
        ),
        migrations.RemoveField(
            model_name='booksource',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='booksource',
            name='added_by',
        ),
    ]
